### ISSUE TITLE
Help with my config file

### ISSUE THREAD

**Issue by djandymarc** [cabernetwork/cabernet#102] opened 2023-08-08 10:33 UTC
Hi there,
I have just setup cabernet and through trial and error managed to get it working great with Pluto TV.
SO i took the next step and adde daddylive.
The Channel list is working fine oon TVHeadend but i cant for the life of me get the EPG to work.

Here is my config file
`[loggers]
keys = root

[logger_root]
level = DEBUG
handlers = loghandler

[handlers]
keys = loghandler, filehandler

[formatters]
keys = extend,simple

[handler_filehandler]
enabled = False
level = INFO
formatter = extend
class = lib.common.log_handlers.MPRotatingFileHandler
args = (os.getenv('LOGS_DIR','data/logs')+'/cabernet.log', 'a', 10000000, 10)

[handler_loghandler]
enabled = True
level = DEBUG
class = StreamHandler
formatter = extend
args = (sys.stdout,)

[formatter_extend]
format = %(asctime)s-%(levelname)s:%(module)s %(message)s

[formatter_simple]
format = %(levelname)s:%(module)s %(message)s

[main]
uuid = D4F0F08C-3204-11EE-B9F2-A01D48C75C55
maintenance_mode = False

[tvguide]
enabled = True

[epg]
genre = tvheadend
epg_prettyprint = True

[tvguide_default]
label = TVGuide Instance
enabled = True

[hdhomerun]
hdhr_id = 105D13F2

[daddylive]
hdhr_id = 10568DA3
enabled = True
epg-plugin = ALL

[daddylive_default]
label = DaddyLive Instance
enabled = True
epg-plugin = ALL
channel-import_groups = False
player-enable_url_filter = False
epg-enabled = True
channel-start_ch_num = 2000

[tvguide_daddylive]
label = TVGuide DaddyLive
enabled = True

[plutotv]
hdhr_id = 105059A4
enabled = True
epg-plugin = ALL

[plutotv_default]
enabled = True
label = PlutoTV Instance
epg-plugin = ALL
channel-thumbnail = colorLogoPNG
epg-enabled = True
channel-start_ch_num = 1000

[tvguide_plutotv]
label = TVGuide PlutoTV
enabled = True`

Any Idea what im doing wrong?
`

**Comment by cookieisland** [comment] 2023-08-08 19:49
Try checking out the 'beginner setup' thread. I think the daddylive EPG and other various other configuration info is discussed there.
https://github.com/cabernetwork/cabernet/issues/78#issuecomment-1504244835

**Comment by rocky4546** [comment] 2023-08-09 02:11
duplicate of #78

**Comment by djandymarc** [comment] 2023-08-14 06:19
Thank you.
I did look at that thread originally but i missed that comment about the tvguide.
After uninstalling the plugin, reinstalling and leaving daddylive at the default chnnel numbers its now getting the EPG.
One thing i did notice was it only has EPG data for the US channels only. Im guessing that is beacuse tvgiode epg plugin is US based?
Any way of getting UK EPG data?
Can you create a copy of the tvgiuide plugin and edit the json file to reflect tvguide.co.uk and add this as a second EPG plugin?

**Closed** 2023-08-31 22:40 UTC
Labels: duplicate
