### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by MartinR577** [cabernetwork/cabernet#85] opened 2023-04-20 23:03 UTC
When I try to upgrade form 0.9.12.03 to 0.9.12.14  I get the following error:

Exception in thread Thread-9 (upgrade_app):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\apps\cabernet\lib\updater\updater.py", line 151, in upgrade_app
    if not app.upgrade_app(STATUS):
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\apps\cabernet\lib\updater\cabernet.py", line 172, in upgrade_app
    if not b.backup_all():
           ^^^^^^^^^^^^^^
  File "C:\apps\cabernet\lib\db\datamgmt\backups.py", line 117, in backup_all
    backup_folder = self.backup_data()
                    ^^^^^^^^^^^^^^^^^^
  File "C:\apps\cabernet\lib\db\datamgmt\backups.py", line 91, in backup_data
    Backup.call_backup(key, self.config, backup_folder=new_backup_path)
  File "C:\apps\cabernet\lib\common\decorators.py", line 232, in call_backup
    inst_fn(**kwargs)
  File "C:\apps\cabernet\lib\db\db_channels.py", line 411, in backup
    self.export_sql(backup_folder)
  File "C:\apps\cabernet\lib\db\db.py", line 304, in export_sql
    export_f.write('%s\n' % line)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 73-76: character maps to <undefined>

I was getting the same error when i tried previous upgrades  on a different windows 10 computer, now i'm on a freashly installed windows 10 computer.

**Comment by rocky4546** [comment] 2023-04-21 00:58
Duplicate of #84

**Comment by rocky4546** [comment] 2023-04-21 01:20
Have not tried this, but if you disable the daddylive instance, restart app, then go to Data Mgmt and delete the daddylive instance, you should be able to run the upgrade. After that, you can reenable the instance, restart app and it should come back up. Any settings in the channel editor would be lost. This is a temp fix until I can get the real fix in…

**Comment by rocky4546** [comment] 2023-04-24 22:37
Fixxed in 0.9.12.15

**Closed by rocky4546** 2023-04-24 22:37 UTC
Labels: duplicate
