### ISSUE TITLE
Admin interface broken

### ISSUE THREAD

**Issue by etofi** [cabernetwork/cabernet#67] opened 2023-04-04 05:36 UTC
I use the last official Docker image ghcr.io/cabernetwork/cabernet:latest
Unfortunately, the admin interface no longer works. No content is loaded in the right frame and the log shows the following error.

`2023-04-04 07:26:58,766-WARNING:main #########################################
2023-04-04 07:26:58,767-WARNING:main MIT License, Copyright (C) 2021 ROCKY4546
2023-04-04 07:27:20,017-ERROR:web_admin UNEXPECTED EXCEPTION on GET='NoneType' object is not iterable
Traceback (most recent call last):
  File "/app/lib/clients/web_admin.py", line 105, in do_GET
    elif getrequest.call_url(self, self.content_path):
  File "/app/lib/common/decorators.py", line 310, in call_url
    self.url2func[_name](_webserver, *args, **kwargs)
  File "/app/lib/web/pages/index_js.py", line 27, in pages_index_js
    _webserver.do_mime_response(200, 'text/javascript', indexjs.get())
  File "/app/lib/web/pages/index_js.py", line 126, in get
    self.check_upgrade_status(),
  File "/app/lib/web/pages/index_js.py", line 40, in check_upgrade_status
    for plugin_defn in plugin_defns:
TypeError: 'NoneType' object is not iterable
2023-04-04 07:27:20,022-WARNING:web_handler [192.168.178.96] "GET /api/index.js HTTP/1.1" 501 -`

**Comment by daza67** [comment] 2023-04-04 10:49
Same here using latest 0.9.12.00 docker image, get same error as etofi above.
`ERROR:web_admin UNEXPECTED EXCEPTION on GET='NoneType' object is not iterable`

Have been struggling to find a version that has working EPG scheduled task function in all the latest releases that have been coming every day, now is really broken.

**Comment by rocky4546** [comment] 2023-04-04 13:23
Working on this issue.  You may want to track #60 as it may be related to Docker issue you are facing.

**Comment by rocky4546** [comment] 2023-04-04 13:37
Looks like the issue is a new install.  No plugins were available causing the issue.  I have a patch which will be ready soon.  If this is not a new install, then you really need to look at how you maintain the data folder, instead of all the pain that would cause.  It should be linked into docker so it does not get deleted.  Also, upgrades should be handled inside the app and not from docker. 

Ultimately, how you use docker is up to you.

**Comment by rocky4546** [comment] 2023-04-04 14:37
Fixed in 0.9.12.01

**Comment by etofi** [comment] 2023-04-04 16:37
Now the admin interface is loaded again but PlutoTV has completely disappeared. In fact, no stream providers are displayed any more. The scheduled tasks for them are also gone.
But there are no errors in the log.

**Comment by etofi** [comment] 2023-04-04 19:44
> Whether you have to re-install the plugins each time is based on your setup. The only time it needs to be installed is on a new installation. Noone has to reinstall the plugin if the plugin_ext folder is externally linked into docker like you should also have the data folder linked.

If I link the plugin_ext folder the installation of the plugin did not work.

**_This works_**
docker create \
--name=cabernet \
--net=macvlan \
--ip 192.168.178.165 \
--restart always \
-e PUID=1000 \
-e PGID=1000 \
-e TZ=Europe/Berlin \
-v /volume1/docker/Cabernet/data:/app/data \
-v /volume1/docker/Cabernet/config.ini:/app/data/config.ini \
ghcr.io/cabernetwork/cabernet:latest

**_This not_**
docker create \
--name=cabernet \
--net=macvlan \
--ip 192.168.178.165 \
--restart always \
-e PUID=1000 \
-e PGID=1000 \
-e TZ=Europe/Berlin \
-v /volume1/docker/Cabernet/data:/app/data \
-v /volume1/docker/Cabernet/plugins_ext:/app/plugins_ext \
-v /volume1/docker/Cabernet/config.ini:/app/data/config.ini \
ghcr.io/cabernetwork/cabernet:latest

**Comment by rocky4546** [comment] 2023-04-04 19:53
First, I still recommend checking out #60 since it is for the docker issues.  Based on what cookieisland has found, it looks like the entire cabernet source needs to be a volume.   On yours, the config.ini should be in the data folder and not a separate volume.  that may be causing some issues, but if you follow what cookieisland recommends, it will fix most of your issues.  The issue that this was initially for has been resolved.  Please followup on issue #60 if you have docker issues.

**Closed by rocky4546** 2023-04-04 19:53 UTC

**Comment by daza67** [comment] 2023-04-04 23:18
Thanks 0.9.12.01 has fixed docker issue for me, still having EPG refresh problem though with one m3u provider, Will open a new issue on that.
