### ISSUE TITLE
any update on a wiki

### ISSUE THREAD

**Issue by aniel300** [cabernetwork/cabernet#188] opened 2024-12-20 12:58 UTC
i can't figure out how to implement this, TIA.

**Comment by ls-milkyway** [comment] 2024-12-20 17:36
> i can't figure out how to implement this, TIA.

It took lot of time to implement on python environment ....but still can't figure out what the settings mean in most of the sections....lot of warnings and errors popping up ....specially when I changed proxy to streamlink and ffmpeg ...internal proxy works best for me...after lot of hit & trail and reading opened and closed issues ...it works, but some channels are not working..... don't know where to put the request to enable them.
Channels are loading fine on local VLC player but takes 8-9 seconds to load from my TV on local network.

**Comment by ls-milkyway** [comment] 2024-12-23 14:13
> a wiki or some samples from the dev would be appreciated

Duplicate of:
https://github.com/cabernetwork/cabernet/issues/22

**Closed** 2024-12-25 09:31 UTC
Labels: duplicate
