### ISSUE TITLE
Windows Errors

### ISSUE THREAD

**Issue by DannysList** [cabernetwork/cabernet#104] opened 2023-09-13 18:34 UTC
Hello,

I'm running this on Win10 almost perfectly and would like to get some help with the remaining issues I'm running into.

I followed your instructions here -> https://github.com/cabernetwork/cabernet/issues/78 for the record.

Issue 1

You said in this post (https://github.com/cabernetwork/cabernet/issues/78#issuecomment-1504244835) that should NOT be listed under EPG Providers. Mine is there and I can't figure out how to remove it. I've uninstalled, rebooted several times, uninstalled tvguide completely and installed it after daddylive was setup, Ive tried rebooting several times, and it still appears under EPG providers

Issue 2

I can't figure out what you meant by auto renumbering here -> https://github.com/cabernetwork/cabernet/issues/78#issuecomment-1504293543. If i'm understanding this correctly, I go to daddy live instance and change the channel start to 100, go to editor and see that all the channels are re-numbered starting with 100. When a new channel comes in is where I'm confused. So when a new channel comes in I have to go back to daddy live instance, set the channel start to 101 hit save then change it back to 100 and hit save again for the new channel to get auto numbered correctly?  

Issue 3

Anytime I dvr something with jellyfin I get an error in Cabernet that says

`2023-09-13 13:38:44,975-INFO:internal_proxy Connection dropped by end device [WinError 10053] An established connection was aborted by the software in your host machine 12860
2023-09-13 13:38:48,579-NOTICE:web_tuner Provider Connection Closed, ch_id=99951126 9704
2023-09-13 13:45:34,674-NOTICE:scheduler Running threaded task EPG:Refresh PlutoTV EPG
2023-09-13 13:45:36,298-INFO:plugin_epg PlutoTV:default EPG update completed
`

I usually only get a minute or so of the program before that happens and doesn't matter what channel i'm on. I know the channel works before I hit record. I'm actually not after anything specific just trying to test everything and set it all up to work correctly. Lastly i have plenty of space on the hard drive and i've recorded other shows with jellyfin on other m3u8 links.

Lastly I've included my config.ini file for you.

3 Suggestions if you don't mind

- I didn't use the docker as docker seems to be above my understanding so I used the windows installer and had it install python and went through that whole setup. If we need python (whatever version) why not make the installer check for it first or give us a option to point to the folder that python is installed in? It is kinda redundant in a sense to have the installer start, install python then cancel the install and restart it when python is installed. Also if it isn't installed why not just make it a "hard limit" where the installer won't go forward unless pytthon is installed before hand. Of course i have 0 coding background so I'm not even sure how to do it let alone if it is possible.

- when restarting from the webui, it gets "stuck" on rebooting because it is looking for python.exe in Files/Python39/ which isn't made. Once I moved the entire python folder into there it worked much much better. Again no coding background so sadly I can't help you. I just have ideas really lol.

- Just to make it "flow better" on github. There should be a template made for anyone who starts a new issue so you (whoever wants to help) can help and get the basics out of the way. Something like

What version of Caberent are you using:
What is your OS:
What is your issue:
**_Github doesn't accept .ini files so please copy your config file from cabernet/data/ to your desktop and rename it config.txt and attach it to this issue:_**

Pretty straight forward I feel, again I don't know all the info you'd need but based off of what I see I feel it would be a good start. I said attach your config file because I feel its easier then pasting it into here which just makes it a wall of text.

[config.txt](https://github.com/cabernetwork/cabernet/files/12600805/config.txt)

**Comment by rocky4546** [comment] 2023-09-13 22:06
With issue 1, the person had EPG Plugin not set to ALL, so there should not be a EPG instance created.  In your case, EPG Plugin is set to ALL, so an EPG instance would be created.  For the step in question, it says after making sure the EPG is gone, ... then set the EPG Plugin to ALL (step 3) restart app and the tvguide will auto turn on.

Issue 2: I have made some changes, so this may work a little different. If you use start ch number, cabernet will compress and renumber the channels.  if you use the EPG Channel Prefix, it will use the actual channel from the provider and add the value to it creating an offset.  In the second case, the channel editor will not show the adjustment since it is applied just before the data is sent to the media server.  If you have the start ch number set, then Cabernet will auto renumber the channels when the channel update task is run.  If no channels changed, then nothing happens.  If a channel is added (lets say "ABC NEWS") then it will alphabetize the list and everything after ABC News will have thier channel number increased by one.  Different media servers handle this differently.  TVHeadend does not change anything, so the channels will be messed up until you rescan the channels in TVHeadend.  Not sure what your server does, although I think it may auto-renumber.  If not you may need to tell jellyfin to somehow update the channel numbers.

Issue #3: This is caused by jellyfin closing the connection.  Normally this happens when jellyfin does not receive data in an appropriate period of time.  You can try turning on "Send ATSC Keep-Alive", which will send an ATSC packet every few seconds until the provider gives cabernet the stream.  Usually, this is caused by media servers than only wait 10 seconds before closing the connection.  In your case, that does not seem to be the case.  I would check to see if cabernet is streaming to jellyfin.  Try bringing up cabernet home page and checking the tuner status.  If it says streaming most of the time, it should be good.  If it says starting and never changes, you have an issue with the provider.  The log would be very helpful.  For windows, it might be easiest to turn on the File Log Handler at either Info or Debug level.

Extra text:
1) it does check for python and will not request python if found.  Even if you have it installed, it may not find it.  Normally once you install it via cabernet, you do not have to install it again.  The installer will know.

2) It uses the path to python.exe when the command python xxx.pyw is run following the install or having is already installed. So, there should not be an issue.

**Comment by DannysList** [comment] 2023-09-13 22:40
wow thanks for the quick reply! what you said makes sense for all my issues. I'll try the atsc keep alive command. Great program here rocky. Definitely surpasses all the other ones I've tried by leaps and bounds.

**Closed** 2023-09-14 03:23 UTC
