### ISSUE TITLE
ads still causing freezing with filtering off - try this

### ISSUE THREAD

**Issue by merrychrishna** [cabernetwork/cabernet#57] opened 2023-03-25 17:05 UTC
ads are still freezing with filtering off. try adding this at the end of m3u links
&serverSideAds=false

#EXTINF:0 tvg-id="rifftrax" tvg-logo="http://images.pluto.tv/channels/58d947b9e420d8656ee101ab/colorLogoPNG.png" group-title="Comedy", RiffTrax
http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/58d947b9e420d8656ee101ab/master.m3u8?advertisingId=&appName=web&appVersion=unknown&appStoreUrl=&architecture=&buildVersion=&clientTime=0&deviceDNT=0&deviceId=1c89e532-8cd3-11ec-9464-73d691707633&deviceMake=Chrome&deviceModel=web&deviceType=web&deviceVersion=unknown&includeExtendedEvents=false&sid=0c52e66c-049b-448e-b438-f0e613af9594&userId=&serverSideAds=false

**Comment by merrychrishna** [comment] 2023-03-25 17:19
oh what the hell. someone how filtering got enabled overnight while i was sleeping. i have just turned it off just now and will continue testing.  but maybe you could still add &serverSideAds=false anyway?

**Comment by merrychrishna** [comment] 2023-03-25 17:31
i just looked at the stream quality in cabernet, somehow it was rest to 1million which causes freezing on transitions to ads when emby is set to 3mbps. i have just now set cabernet plutotv stream quality to 500k and will conitnue to test.

**Comment by merrychrishna** [comment] 2023-03-25 17:45
no its still freezing on transitions to ads

**Comment by merrychrishna** [comment] 2023-03-25 18:08
its still freezing on ads

![image](https://user-images.githubusercontent.com/59185469/227734088-f27df889-8ecd-4957-addb-918114083aa9.png)


heres the log
[cabernet.log](https://github.com/cabernetwork/cabernet/files/11069717/cabernet.log)

**Comment by merrychrishna** [comment] 2023-03-25 18:08
gotta get rid of the ads with &serverSideAds=fals

**Comment by merrychrishna** [comment] 2023-03-25 18:26
pluginsext is still empty


![image](https://user-images.githubusercontent.com/59185469/227734984-37dd2d89-5e06-471d-a42e-adcd77500842.png)

**Comment by rocky4546** [comment] 2023-03-25 18:37
plugin_ext is managed currently by you. since you have not put anything there, nothing is there.

**Comment by rocky4546** [comment] 2023-03-25 18:39
with &serverSideAds=false, I get the same ads as without.  I see no difference.

**Comment by merrychrishna** [comment] 2023-03-25 18:41
does my logs tell you why im freezing when it goes to an ad?

**Comment by merrychrishna** [comment] 2023-03-25 18:44
am i stuck on streamlinkproxy even though its set to internal proxy?

**Comment by rocky4546** [comment] 2023-03-25 18:46
With filtering off, the video freeze is caused by ffmpeg unable to process the resync request due to the DTS/PTS data is corrupted.  It is seen in the log as "Restarting PTSResync ffmpeg due to no ffmpeg processing".  Also, a log entry shows when ffmpeg crashes associated with a bad stream with "FFMPEG ERRCODE: 1, unable for pts_resync to process segment in ffmpeg"

**Comment by rocky4546** [comment] 2023-03-25 18:47
should not be stuck on streamlink.

**Comment by merrychrishna** [comment] 2023-03-25 18:47
[config.ini.txt](https://github.com/cabernetwork/cabernet/files/11069815/config.ini.txt)


ok so is that something i need to fix on my end?

**Comment by rocky4546** [comment] 2023-03-25 18:48
have no clue what the issue is

**Comment by merrychrishna** [comment] 2023-03-25 18:51
ill try rebooting my pc but ill have to do that in an hour because im transferring a lot of files right now between drives and says its going to take an hour

**Comment by rocky4546** [comment] 2023-03-25 18:52
still have no idea what the issue is.  There is no issue with the app.

**Comment by rocky4546** [comment] 2023-03-25 18:55
you can try restarting the app through the scheduler...

**Comment by merrychrishna** [comment] 2023-03-25 19:06
ok tried it just now and changed the channel but it still freezes. im going to try stopping all my serevres processes and start them back up.

**Comment by merrychrishna** [comment] 2023-03-25 19:16
its still freezing. maybe it has something to do with my low bandwidth and ads quality i snot being reduced to 500k, only the actual movies or shows are in 500k?

**Comment by rocky4546** [comment] 2023-03-25 19:18
don't see a difference in streaming quality when ads are on.  what channels are you referring to

**Comment by merrychrishna** [comment] 2023-03-25 19:18
comedy central, comedy central animation. mystery science theater 3000.

**Comment by merrychrishna** [comment] 2023-03-25 19:23
how about adding something like what ersatz tv has? the work ahead and hls settings help with transitions 
![image](https://user-images.githubusercontent.com/59185469/227737233-0a273d97-871b-4e88-bcd2-ddbbc3ede254.png)


also in ersatz tv his new mpegts mode helps me with transitions too. not his legacy mpegts though. the new mpegs properly stitches the streams together better than his other modes. he recommened i use hls segmenter instead but i tried it and it doesnt play well with emby.

**Comment by merrychrishna** [comment] 2023-03-25 19:26
![image](https://user-images.githubusercontent.com/59185469/227737342-17d8f892-99b7-43c9-ad40-d73730d4bfa0.png)

![image](https://user-images.githubusercontent.com/59185469/227737361-58e1f415-fcee-40a4-a8b6-a78983c12132.png)


these are just some ideas for features you can add in cabernet to help with my issue hopefully.

**Comment by rocky4546** [comment] 2023-03-25 20:14
Checked on a bunch of comedy channels and found something different than what I found on the funny channels.  Although some of the issues were resolved, the problems with the comedy ads mess up the PTS/DTS so bad it cannot be resolved.  Trying to just play one ts segment in VLC fails showing just how bad these segments are.  At this point, I cannot find any fix that would allow the ads to play in a video player.  My only thought is that the player must not look at the PTS/DTS data to play, which I do not know of one that does that.
This issue will be closed as wont fix.

**Comment by merrychrishna** [comment] 2023-03-25 21:39
will they play in a browser?

**Comment by rocky4546** [comment] 2023-03-25 21:46
nope. in fact, VLC does not believe they are a stream and displays the binary text instead of playing it.  Tried all the players I had and put in the browser.  In order to fix this, I would have to write my own PTS/DTS converter, which right now is not on the list.  So, won't fix.

**Comment by rocky4546** [comment] 2023-03-25 22:04
Doing a little more research on CMCD requests to see if that will help...

**Comment by rocky4546** [comment] 2023-03-25 23:31
OK, final try failed.  CMCD did not resolve issue.  Updated m3u8 url with all possible query items. did not fix issue.  Looks like they are doing what I said.  They are updating the DTS/PTS stream data based on a query to  
https://infinity-c19.youboranqs01.com/infinity/session/beat?timemark=1679784838464&accountCode=plutotv&sessionRoot=(redacted)&sessionId=(redacted)
and then making updates. So not going to happen for now.

**Closed** 2023-03-25 23:31 UTC
Labels: wontfix

**Comment by merrychrishna** [comment] 2023-03-26 03:06
you dont need to make a converter. streamlink has a plutotv plugin built into streamlink that automatically filters out all the ads and commercials. while its filtering the ads and commercials we have to stare at a frozen screen but at least its not frozen forever and it resumes playing after the freez. thats why i was suggesting that you could do something like allow cabernet to detect when filtering starts and could just play a saved pluto tv screensaver splash screen video until cabernet detects the ads and commercials have finished and then it resumes playing the channel.



a seperate issue i have a problem with streamlink where sometimes when returning from the frozen screen from ads and comercials it sometime stays frozen but i can hear audio of the actual show resuming after the commercial and plays the rest of the shows audio only until i exit the channel and play the channel again.
